server:
  port: 8080
spring:
  application:
    name: activitycrud-service
    profiles:
      active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/activity?currentSchema=activity
    driver-class-name: org.postgresql.Driver
    initialize: false
    tomcat:
      max-idle: 1
      max-active: 5
      initial-size: 5
      min-idle: 0
      max-age: 901000
      time-between-eviction-runs-millis: 13000
      min-evictable-idle-time-millis: 61000
      remove-abandoned: true
      remove-abandoned-timeout: 3601
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    com.kmstechnology.activitycrud: DEBUG
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG