spring:
  main:
    web-environment: false
    web-application-type: none
  application:
    name: activity-crud-migration
    profiles:
      active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/activity_manager?currentSchema=schema_activity_manager
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    initialize: false
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
  level:
    com:
      kmstechnology:
        activitycrud: INFO
    org:
      flywaydb: INFO